
import java.awt.Color;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Usuario
 */

public class CrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CrNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        CrContraseña = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        CrUsuario = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        CrApellido = new javax.swing.JTextField();
        LoginBtn = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(233, 164, 39));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/20240428_145843 (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 120));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de Gestión de Horas Libres");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(0, 556, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        jPanel2.setBackground(new java.awt.Color(233, 142, 45));
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 410));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, 960));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setText("Crear Cuenta");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Nombre");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        CrNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CrNombre.setForeground(new java.awt.Color(153, 153, 153));
        CrNombre.setText("Ingrese su nombre");
        CrNombre.setBorder(null);
        CrNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CrNombreMousePressed(evt);
            }
        });
        bg.add(CrNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 200, 10));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Apellido");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        CrContraseña.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CrContraseña.setForeground(new java.awt.Color(153, 153, 153));
        CrContraseña.setText("Ingrese su nueva contraseña");
        CrContraseña.setBorder(null);
        CrContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CrContraseñaMousePressed(evt);
            }
        });
        CrContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrContraseñaActionPerformed(evt);
            }
        });
        bg.add(CrContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 200, 10));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Usuario");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        CrUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CrUsuario.setForeground(new java.awt.Color(153, 153, 153));
        CrUsuario.setText("Ingrese su nuevo usuario");
        CrUsuario.setBorder(null);
        CrUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CrUsuarioMousePressed(evt);
            }
        });
        bg.add(CrUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 200, 10));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Contraseña");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 200, 10));

        CrApellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CrApellido.setForeground(new java.awt.Color(153, 153, 153));
        CrApellido.setText("Ingrese su primer apellido");
        CrApellido.setBorder(null);
        CrApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CrApellidoMousePressed(evt);
            }
        });
        CrApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrApellidoActionPerformed(evt);
            }
        });
        bg.add(CrApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        LoginBtn.setBackground(new java.awt.Color(233, 164, 39));
        LoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBtn.setPreferredSize(new java.awt.Dimension(117, 29));
        LoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LoginBtnMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("INICIAR SESIÓN");

        javax.swing.GroupLayout LoginBtnLayout = new javax.swing.GroupLayout(LoginBtn);
        LoginBtn.setLayout(LoginBtnLayout);
        LoginBtnLayout.setHorizontalGroup(
            LoginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginBtnLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        LoginBtnLayout.setVerticalGroup(
            LoginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        bg.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/UNABFONDOO.jpg"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(378, 959));
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 280, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrContraseñaActionPerformed

    private void CrApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrApellidoActionPerformed

    private void LoginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseEntered
        LoginBtn.setBackground(new Color(237, 182, 82));
    }//GEN-LAST:event_LoginBtnMouseEntered

    private void LoginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseExited
        LoginBtn.setBackground(new Color(233, 164, 39));
    }//GEN-LAST:event_LoginBtnMouseExited

    private void LoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseClicked

        String nombre = CrNombre.getText();
        String apellido = CrApellido.getText();
        String usuario = CrUsuario.getText();
        String contraseña = CrContraseña.getText();

        if (!nombre.equals("Ingrese su nombre") && !apellido.equals("Ingrese su primer apellido") && !usuario.equals("Ingrese su nuevo usuario") && !contraseña.equals("Ingrese su nueva contraseña")) {
            try {
                UsuariosDAO.guardarUsuario(nombre, apellido, usuario, contraseña);

                CrNombre.setText("");
                CrApellido.setText("");
                CrUsuario.setText("");
                CrContraseña.setText("");
                
                JOptionPane.showMessageDialog(this, "Cuenta creada correctamente", "Excelente!", JOptionPane.INFORMATION_MESSAGE);
                Login abrir = new Login();
                abrir.setVisible(true);
                this.setVisible(false);
                
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al crear la cuenta", "Vaya", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
        }
    }//GEN-LAST:event_LoginBtnMouseClicked

    private void CrNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrNombreMousePressed

        if (CrNombre.getText().equals("Ingrese su nombre")) {
            CrNombre.setText("");
            CrNombre.setForeground(Color.black);
        }

        if (CrApellido.getText().isEmpty()) {
            CrApellido.setText("Ingrese su primer apellido");
            CrApellido.setForeground(Color.gray);
        }

        if (CrUsuario.getText().isEmpty()) {
            CrUsuario.setText("Ingrese su nuevo usuario");
            CrUsuario.setForeground(Color.gray);
        }

        if (CrContraseña.getText().isEmpty()) {
            CrContraseña.setText("Ingrese su nueva contraseña");
            CrContraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_CrNombreMousePressed

    private void CrApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrApellidoMousePressed

        if (CrNombre.getText().isEmpty()) {
            CrNombre.setText("Ingrese su nombre");
            CrNombre.setForeground(Color.gray);
        }

        if (CrApellido.getText().equals("Ingrese su primer apellido")) {
            CrApellido.setText("");
            CrApellido.setForeground(Color.black);
        }

        if (CrUsuario.getText().isEmpty()) {
            CrUsuario.setText("Ingrese su nuevo usuario");
            CrUsuario.setForeground(Color.gray);
        }

        if (CrContraseña.getText().isEmpty()) {
            CrContraseña.setText("Ingrese su nueva contraseña");
            CrContraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_CrApellidoMousePressed

    private void CrUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrUsuarioMousePressed

        if (CrNombre.getText().isEmpty()) {
            CrNombre.setText("Ingrese su nombre");
            CrNombre.setForeground(Color.gray);
        }

        if (CrApellido.getText().isEmpty()) {
            CrApellido.setText("Ingrese su apellido");
            CrApellido.setForeground(Color.gray);
        }

        if (CrUsuario.getText().equals("Ingrese su nuevo usuario")) {
            CrUsuario.setText("");
            CrUsuario.setForeground(Color.black);
        }

        if (CrContraseña.getText().isEmpty()) {
            CrContraseña.setText("Ingrese su nueva contraseña");
            CrContraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_CrUsuarioMousePressed

    private void CrContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrContraseñaMousePressed

        if (CrNombre.getText().isEmpty()) {
            CrNombre.setText("Ingrese su nombre");
            CrNombre.setForeground(Color.gray);
        }

        if (CrApellido.getText().isEmpty()) {
            CrApellido.setText("Ingrese su apellido");
            CrApellido.setForeground(Color.gray);
        }

        if (CrUsuario.getText().isEmpty()) {
            CrUsuario.setText("Ingrese su nuevo usuario");
            CrUsuario.setForeground(Color.gray);
        }

        if (CrContraseña.getText().equals("Ingrese su nueva contraseña")) {
            CrContraseña.setText("");
            CrContraseña.setForeground(Color.black);
        }
    }//GEN-LAST:event_CrContraseñaMousePressed


    private void LoginBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMousePressed
        //nada
    }//GEN-LAST:event_LoginBtnMousePressed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new CrearCuenta().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CrApellido;
    private javax.swing.JTextField CrContraseña;
    private javax.swing.JTextField CrNombre;
    private javax.swing.JTextField CrUsuario;
    private javax.swing.JPanel LoginBtn;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
