
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class PagInicio extends javax.swing.JFrame {
    private String nombreUsuario;
    
    public PagInicio(String nombreUsuario) {
        initComponents();
        this.nombreUsuario = nombreUsuario;
        msjBienvenida.setText("Hola " + nombreUsuario + "." + " Bienvenido a UNABGO!");
    }
    /**
     * Creates new form PagInicio
     */
    public PagInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        msjBienvenida = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HorasCRUDBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PromediosBtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        InfoEventosBtn = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(233, 164, 39));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/20240428_145843 (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 120));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de Gestión de Horas Libres");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(0, 556, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        jPanel2.setBackground(new java.awt.Color(233, 142, 45));
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 410));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, 600));

        msjBienvenida.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        msjBienvenida.setText("Bienvenido a UNABGO!");
        bg.add(msjBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jLabel3.setText("¡Asiste a eventos y consigue beneficios!");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        HorasCRUDBtn.setBackground(new java.awt.Color(233, 164, 39));
        HorasCRUDBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HorasCRUDBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HorasCRUDBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HorasCRUDBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HorasCRUDBtnMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("HÁZLO AHORA!");

        javax.swing.GroupLayout HorasCRUDBtnLayout = new javax.swing.GroupLayout(HorasCRUDBtn);
        HorasCRUDBtn.setLayout(HorasCRUDBtnLayout);
        HorasCRUDBtnLayout.setHorizontalGroup(
            HorasCRUDBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HorasCRUDBtnLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(38, 38, 38))
        );
        HorasCRUDBtnLayout.setVerticalGroup(
            HorasCRUDBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HorasCRUDBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        bg.add(HorasCRUDBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 180, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("de horas libres que deberías de completar?");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Conoce el estado de tus horas libres y cómo podrás completarlas con los");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("eventos vigentes que la UNAB ofrece.");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imageSS.jpg"))); // NOI18N
        jLabel8.setToolTipText("");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 460, 150));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setText("¿Deseas gestionar tus horas libres?");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setText("Obtén información sobre los eventos disponibles:");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, -1, -1));

        PromediosBtn.setBackground(new java.awt.Color(233, 164, 39));
        PromediosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PromediosBtn.setPreferredSize(new java.awt.Dimension(180, 30));
        PromediosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PromediosBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PromediosBtnMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONÓCELOS");

        javax.swing.GroupLayout PromediosBtnLayout = new javax.swing.GroupLayout(PromediosBtn);
        PromediosBtn.setLayout(PromediosBtnLayout);
        PromediosBtnLayout.setHorizontalGroup(
            PromediosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PromediosBtnLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(47, 47, 47))
        );
        PromediosBtnLayout.setVerticalGroup(
            PromediosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PromediosBtnLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        bg.add(PromediosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel12.setText("¿Sabes cuáles son los promedios");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, -1, -1));

        InfoEventosBtn.setBackground(new java.awt.Color(233, 164, 39));
        InfoEventosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InfoEventosBtn.setPreferredSize(new java.awt.Dimension(180, 30));
        InfoEventosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InfoEventosBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InfoEventosBtnMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("QUIERO SABER MÁS!");

        javax.swing.GroupLayout InfoEventosBtnLayout = new javax.swing.GroupLayout(InfoEventosBtn);
        InfoEventosBtn.setLayout(InfoEventosBtnLayout);
        InfoEventosBtnLayout.setHorizontalGroup(
            InfoEventosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoEventosBtnLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel13)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        InfoEventosBtnLayout.setVerticalGroup(
            InfoEventosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoEventosBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        bg.add(InfoEventosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HorasCRUDBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HorasCRUDBtnMouseEntered
        HorasCRUDBtn.setBackground (new Color(237, 182, 82));
    }//GEN-LAST:event_HorasCRUDBtnMouseEntered

    private void HorasCRUDBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HorasCRUDBtnMouseExited
        HorasCRUDBtn.setBackground (new Color(233, 164, 39));
    }//GEN-LAST:event_HorasCRUDBtnMouseExited

    private void PromediosBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PromediosBtnMouseEntered
        PromediosBtn.setBackground (new Color(237, 182, 82));
    }//GEN-LAST:event_PromediosBtnMouseEntered

    private void PromediosBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PromediosBtnMouseExited
        PromediosBtn.setBackground (new Color(233, 164, 39));
    }//GEN-LAST:event_PromediosBtnMouseExited

    private void InfoEventosBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoEventosBtnMouseEntered
        InfoEventosBtn.setBackground (new Color(237, 182, 82));
    }//GEN-LAST:event_InfoEventosBtnMouseEntered

    private void InfoEventosBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoEventosBtnMouseExited
        InfoEventosBtn.setBackground (new Color(233, 164, 39));
    }//GEN-LAST:event_InfoEventosBtnMouseExited

    private void HorasCRUDBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HorasCRUDBtnMouseClicked
        HorasLibresCRUD abrir = new HorasLibresCRUD();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HorasCRUDBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HorasCRUDBtn;
    private javax.swing.JPanel InfoEventosBtn;
    private javax.swing.JPanel PromediosBtn;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel msjBienvenida;
    // End of variables declaration//GEN-END:variables
}
